spring:
  application:
    name: springHomework03

    issue:
      max_allowed_books:
        3
  datasource:
    url: jdbc:mysql://localhost:3306/SpringDB?createDatabaseIfNotExist=TRUE
    username: root
    password: 11*******
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate.ddl-auto: update
    generate-ddl: true

